# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-BeyondPerl-ToSQL
version:      0.01
version_from: lib/Acme/BeyondPerl/ToSQL.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
